project:
  type: book

book:
  page-navigation: true
  title: Alaskan Community Ontology 
  author: Alaska Center for Energy and Power (ACEP) at the University of Alaska Fairbanks (UAF)
  description: A vocabulary of entities that describe Alaskan communities, aggregates of communities such as grids and regions, and the relationships between them.  
  site-url: https://acep-aedg.github.io/alaskan-community-ontology
  repo-url: https://github.com/acep-aedg/alaskan-community-ontology
  repo-actions: [issue]
  downloads: [pdf]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; [CC BY-SA 4.0](https://github.com/acep-aedg/alaskan-community-ontology/blob/main/LICENSE), 2025<br /> [Alaska Center for Energy and Power](https://www.uaf.edu/acep/)"
    center: "The [University of Alaska](www.alaska.edu) is an Equal Opportunity/Equal Access Employer and Educational Institution.  The University is committed to a [policy of non-discrimination](www.alaska.edu/nondiscrimination) against individuals on the basis of any legally protected status."

    
  sidebar:
    logo: "images/aedg_logo_color_300ppi.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.uaf.edu/acep/   # in future, replace with AEDG URL
        text: "Alaska Center for Energy and Power"

  chapters:
    - index.qmd
    - community_classes.qmd
    - electricity_classes.qmd
    - energy_classes.qmd
    - relations.qmd
    - axioms.qmd
    - about.qmd
  appendices:
    - legal_definitions.qmd
    - ipp_utility_example.qmd
    - grids.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt # LaTex document class as implemented by KOMA-script (book, report, article, letter)
    toc: true
    lof: false
    lot: false

filters:
  - quarto


