---
title: "Classes"
subtitle: "Types of entities in the Alaska Community Ontology"
author:
  - name: Liz Dobbins
    url: https://github.com/eldobbins
    affiliation: "Alaska Center for Energy and Power, University of Alaska Fairbanks"
    affiliation-url: https://www.uaf.edu/acep 
type: webpage
date: 2024-11-12
---

## Classes

Classes are types of entities. Most are defined according to existing legal structures as described in the linked references. The main exception is Community, which is the organizational principle of previous versions of AEDG; we will define that one ourselves. It is likely we can use established standard vocabularies to define all Classes. Which standard we use will depend on the level of specificity we want.  

  - Classes could be translated to tables in a relational database, if that makes sense for development. 
  - Instances of a Class are nodes in a graph, if you think about things that way.
  - Classes are typically capitolized to differentiate them from instances or objects of that class, which are lower case.

This page also includes Properties, which are attributes of the Classes. 

  - Properties could take the form of columns in tables in a relational database.


## Applicable Standards

[Schema.org](https://schema.org) is a widely used classification scheme built around web semantics - so more applicable to internet based services, of which AEDG is one.

[Dublin Core Metadata Terms (DCMT)](https://www.dublincore.org/specifications/dublin-core/dcmi-terms) are limited to only the most necessary terms. For instance, [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location) is defined to include both spatial regions and named places, and puts no qualifications on the type or context. Similarly, an [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) is merely "a resource that acts or has the power to act". [Wikipedia says](https://en.wikipedia.org/wiki/Dublin_Core): "Initially developed as fifteen terms in 1998 the set of elements has grown over time and in 2008 was redefined as **an** Resource Description Framework (RDF) vocabulary."

OEO is the [Open Energy Ontology](http://openenergy-platform.org/ontology/oeo/), which you access via this [Terminology Service](https://terminology.tib.eu/ts/ontologies/oeo/terms).

If the Census terms don't make sense, check the [Census Glossary](https://www.census.gov/glossary/).

Terms describing Alaska Native representation are complex. The definitions here are based on [ANCSA Regional Association's Overview](https://ancsaregional.com/overview-of-entities/), is a description of the different tribal entities in Alaska that includes links to more information.


## Common Properties

These are attributes shared by all Classes

- id (int): All Classes should have an id column for inclusion in lookup tables. 
  - How we determine these is a whole 'nother thing.
- label (string): Human readable name. This cannot be the key of the table becaues multiple Classes could have the same label (example: Fairbanks the Municipality and Fairbanks the Borough)
- classModificationDate (time): Classes will evolve as we evaluate their effectiveness, so we should record when the class definition changes to identify which Classes might need reevaluation. 
- entityModificationDate (time): This is to allow evolution in time.
- geometry (geom): As it is developing, each of these entities seems to have spatial component, though it might be a Point, Polygon, or Line.


# List of Classes

## AEDG Context Only

### Communities
- **Definition**: Construct of AEDG that is the fundamental unit of displays and dashboards.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/Place
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
- **Properties**:
  - geometry (WKT Point): longitude, latitude of the Community for convenience of display. Perhaps the centroid of the Municipality or a commonly accepted "place".


## ANCSA or Indigenous Context

### FedRecognizedTribes
- **Definition**: For the purposes of tracking energy in Alaska, the definition [should|will|could] be restricted to the 229 Federally recognized Tribes - sovereign governments. The 1975 Indian Self-Determination and Education Assistance Act allows tribes to contract with the federal government to provide services in place of federal agencies. 
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/GovernmentOrganization
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
- **References**:
  - https://biamaps.geoplatform.gov/BIA-Opendata/Data/ - terrible. no way to link to dataset.
  - https://www.fws.gov/sites/default/files/documents/Map-Federally-Recognized-Tribes-In-Alaska.pdf
  - https://www.scotusblog.com/2021/04/are-alaska-native-corporations-indian-tribes-a-multimillion-dollar-question
  - https://biamaps.geoplatform.gov/Tribal-Leaders-Directory/
- **Properties**:
  - geometry (WKT Polygon): boundary of Tribe
  - Additional properties should be determined by what is important to the people. i.e. language?


### VillageCorps
- **Definition**: Alaska Native village corporations were created by the Alaska Native Claims Settlement Act (ANCSA) and are organized around small communities in Alaska that typically stemmed from traditional Alaska Native land. Village corporations were intended to select lands on which any part of the village was located. Their importance in the energy context is that they might operate as Independent Power Producers that sell power to the Communities' utilities. 
- **SpatialRelationships**: 
  - WITHIN Alaska
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
  - Is an [foaf:Organization](http://xmlns.com/foaf/spec/#term_Organization) that is [foaf:based_near](http://xmlns.com/foaf/spec/#term_based_near) a Community - "A location that something is based near, for some broadly human notion of near."
- **References**:
  - https://dcra-cdo-dcced.opendata.arcgis.com/datasets/DCCED::native-village-corporations/ (215 records)
  - https://ancsa.lbblawyers.com/1602.htm (definition)
  - https://ancsa.lbblawyers.com/native-corporations.htm (list of 179)
  - https://ancsaregional.com/about-ancsa/#mandates
- **Properties**:
  - geometry (WKT Point): longitude, latitude of tribal leadership location
  - related to Communities via the `is_based_near` lookup table.
  - Additional properties should be determined by what is important to the people.


### RegionalCorps
- **Definition**: Alaska Native regional corporations were created by the Alaska Native Claims Settlement Act (ANCSA) and are organized around geographic areas defined by the common heritage and shared interests of the indigenous peoples. The boundaries of these areas do not directly represent land ownership, but instread define the areas in which each regional corporation could select lands to be conveyed under the provisions of ANCSA.
- **SpatialRelationships**: 
  - WITHIN Alaska
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
- **References**:
  - https://www.arcgis.com/home/item.html?id=c78df0004ab845a9a32697d9c20d09e0
  - https://catalog.data.gov/dataset/tiger-line-shapefile-2017-state-alaska-current-alaska-native-regional-corporation-anrc-state-ba
  - https://ancsa.lbblawyers.com/native-corporations.htm (list of 13)
  - https://ancsaregional.com/about-ancsa/#mandates
  - https://maps.commerce.alaska.gov/server/rest/services/ANCSA/ANCSA_Corporations/MapServer
- **Properties**:
  - geometry (WKT Polygon): boundary of the RegionalCorp.
  - Additional properties should be determined by what is important to the people.


## Administrative Context

### IncorporatedPlaces
- **Definition**: Incorporated places are legally incorporated under state law, have a legally defined boundary, and an active functioning governmental structure. Examples of incorporated places include cities, towns, villages, etc. (Not boroughs in Alaska)
- **SpatialRelationships**: 
  - WITHIN Boroughs
  - WITHIN Precincts
  - WITHIN HouseDistricts
  - WITHIN SenateDistricts
- **Analogous Standards**:
  - https://schema.org/GovernmentOrganization
  - has an https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location) for the place
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) for the government
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.  Governmental ok?
- **References**:
  - https://www.census.gov/programs-surveys/bas/information/cdp.html
  - https://www2.census.gov/programs-surveys/popest/tables/2020-2023/cities/totals/SUB-IP-EST2023-POP-02.xlsx 2023 populations for Alaska incorporated places
- **Properties**:
  - geometry (WKT Polygon): boundary 


### CensusDesignatedPlaces
- **Definition**: CDPs are statistical equivalents of incorporated places and represent unincorporated communities that do not have a legally defined boundary or an active, functioning governmental structure. They are locally recognized and identified by name. Examples of CDPs include unincorporated communities, planned communities, military installments, university towns, resort towns, etc. 
- **SpatialRelationships**: 
  - WITHIN Boroughs
  - WITHIN Precincts
  - WITHIN HouseDistricts
  - WITHIN SenateDistricts
- **Analogous Standards**:
  - https://schema.org/Place
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
- **References**:
  - https://www.census.gov/programs-surveys/bas/information/cdp.html
- **Properties**:
  - location (WKT Point): longitude, latitude points of whereever the census says it is (does not have legal boundary, therefore not a polygon?)


### Boroughs
- **Definition**: Boroughs are analagous to a county in other places. Organized boroughs were formed in those areas where economies were better developed. The remaining areas are the unorganized borough, which is divided into census areas; these areas exist for statistical analysis and do not have a government of their own. There are also consolidated city-borough governments.
- **SpatialRelationships**: 
  - CONTAINS IncorporatedPlaces
  - CONTAINS CensusDesignatedPlaces
  - OVERLAPS Precincts
  - OVERLAPS HouseDistricts
  - OVERLAPS SenateDistricts
- **Analogous Standards**:
  - https://schema.org/GovernmentOrganization
  - has an https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location) for the place
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) for the government
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of Alaska)
  - OEO:provider (an organization with a role) provides a governmental OEO:service
- **References**:
  - https://gis.data.alaska.gov/datasets/DCCED::alaska-borough-and-census-area-boundaries/about
  - https://www.commerce.alaska.gov/web/dcra/LocalBoundaryCommission
  - https://en.wikipedia.org/wiki/List_of_boroughs_and_census_areas_in_Alaska
  - https://live.laborstats.alaska.gov/cen/maps/state/current/AlaskaBorCA.pdf
  - https://live.laborstats.alaska.gov/cen/maps/bor/current/090.pdf map of FNSB with cities and census
- **Properties**:
  - type (string): "Unified Home Rule", "Non-unified Home Rule", "First Class", "Second Class"
  - geometry (WKT MultiPolygon): boundary of the Borough


### HouseDistricts
- **Definition**: The Alaska State House is the lower house in the Alaska State Legislature. Its districts are determined on the basis of population and shall be "contiguous and compact territory containing nearly as possible a relatively integrated socioeconomic area"
- **SpatialRelationships**: 
  - CONTAINS IncorporatedPlaces
  - CONTAINS CensusDesignatedPlaces
  - CONTAINS Precincts
  - WITHIN SenateDistricts
- **Analogous Standards**:
  - https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of Alaska and of SenateDistrict)
- **References**:
  - https://maps.commerce.alaska.gov/server/rest/services/Govt_Related/Govt_House_and_Senate_Districts/MapServer
  - https://www.elections.alaska.gov/doc/forms/H07.pdf list of senate and house districts
  - https://www.elections.alaska.gov/doc/forms/H32COM.pdf community/district lists
  - https://akleg.gov/pages/legbranch.php
- **Properties**:
  - district (int): digit that denotes the district
  - geometry (WKT MultiPolygon): boundary of the district.


### SenateDistricts
- **Definition**: Alaska State Senate is the upper house in the Alaska State Legislature. Its districts are composed of two contiguous house districts, if possible.
- **SpatialRelationships**: 
  - CONTAINS IncorporatedPlaces
  - CONTAINS CensusDesignatedPlaces
  - CONTAINS Precincts
  - CONTAINS HouseDistricts
- **Analogous Standards**:
  - https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of Alaska)
- **References**:
  - https://maps.commerce.alaska.gov/server/rest/services/Govt_Related/Govt_House_and_Senate_Districts/MapServer
 - https://www.elections.alaska.gov/doc/forms/H07.pdf list of senate and house districts
 - https://www.elections.alaska.gov/doc/forms/H32COM.pdf community/district lists
 - https://akleg.gov/pages/legbranch.php
- **Properties**:
  - district (character): Capitol letter that denotes the district
  - geometry (WKT MultiPolygon): boundary of the district.


## Statistical or Research Context

### CensusBlocks
- **Definition**: Census blocks are the smallest level of geography you can get basic census demographic data for, such as total population by age, sex, and race.
- **SpatialRelationships**: 
  - WITHIN CensusTracts
- **Analogous Standards**:
  - https://schema.org/DefinedRegion - Arbitrary!  haha
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:study subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020034) (of CensusTract)
- **References**:
  - https://www.census.gov/newsroom/blogs/random-samplings/2011/07/what-are-census-blocks.html
  - https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geopackage-file.html
  - https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html
  - https://live.laborstats.alaska.gov/article/maps-gis-data
- **Properties**:
  - geometry (WKT Polygon): boundary of the census block.


### CensusTracts
- **Definition**: Census tracts are small, relatively permanent statistical subdivisions of a county or statistically equivalent entity that provide a stable set of geographic units for the presentation of statistical data.
- **SpatialRelationships**: 
  - CONTAINS CensusBlocks
- **Analogous Standards**:
  - https://schema.org/DefinedRegion - Arbitrary!  haha
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:study region](http://openenergy-platform.org/ontology/oeo/OEO_00020032) - "A study region is a region of relevance that has the study region role and consists entirely of one or more subregions."
- **References**:
  - https://www.census.gov/programs-surveys/geography/about/glossary.html#par_textimage_13
  - https://esri.maps.arcgis.com/home/item.html?id=20f5d275113e4066bf311236d9dcc3d4
  - https://live.laborstats.alaska.gov/article/maps-gis-data
- **Properties**:
  - geometry (WKT Polygon): boundary of the census tract.


### Regions
- **Definition**: Communities have been grouped into Regions in order to summarize energy trends in the Energy Statistics Workbooks or the Alaska Electricity Trends Report (2024). If new regions are defined, they can be included, but this is intended to be either AEA's 11 regions or ACEP's 3 regions (Coastal, PCE, or Railbelt).  Note: if we need to translate between AEA and ACEP regions, we will need to separate these.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/DefinedRegion - Arbitrary!  haha
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:study region](http://openenergy-platform.org/ontology/oeo/OEO_00020032) - "A study region is a region of relevance that has the study region role and consists entirely of one or more subregions."
- **Properties**:
  - organizaton (string): 'ACEP' or 'AEA' as the origanization that defined the region. 
  - ~~boundary (WKT Polygon):~~ A spatial boundary does not make sense because these were used to group communities together, and in the case of ACEP's regions, they were intended to be discontinuous. Meaning, there are some PCE communities that are pretty near the coast because the designation is based on power costs and not geography. Could be solved with multipolygon or lookup table.
  - geometry (WKT MultiPolygon): proposed geometry 


## Energy Context


### Grids
- **Definition**: An Electric power grid is "A system of synchronized power providers and consumers connected by transmission and distribution lines and operated by one or more control centers. ... In Alaska and Hawaii, several systems encompass areas smaller than the State (e.g., the interconnect serving Anchorage, Fairbanks, and the Kenai Peninsula)" (EIA)
- **SpatialRelationships**: 
  - CONTAINS PowerLines (transmission and distribution lines)
  - CONTAINS PowerStations (power providers)
  - CONTAINS Communities (consumers) ?
- **Analogous Standards**:
  - [dc:PhysicalResource](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/PhysicalResource)
  - [OEO:electricity grid](http://openenergy-platform.org/ontology/oeo/OEO_00000143) -  "An electricity grid is a supply grid that distributes electrical energy / electricity." It is an aggregate of material entities that has parts: power stations and power lines.
- **References**:
  - https://www.eia.gov/tools/glossary/index.php?id=Electric%20utility
- **Properties**:
  - microgrid (boolean): True/False (need a definition for this)
  - capacity (int): megawatts MW
  - geometry (WKT Polygon): All grids are continuous. Could this be a shape that includes all the PowerPlants and PowerLines?


### Utilities
- **Definition**: "A corporation, person, agency, authority, or other legal entity or instrumentality aligned with distribution facilities for delivery of electric energy for use primarily by the public. Included are investor-owned electric utilities, municipal and State utilities, Federal electric utilities, and rural electric cooperatives." (EIA)
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
  - [OEO:power plant operator](http://openenergy-platform.org/ontology/oeo/OEO_00140130) - "an agent that operates an electric utility generation station."
- **References**:
  - https://www.eia.gov/tools/glossary/index.php?id=Electric%20utility
- **Properties**:
  - coop (boolean): True/False is it organized as a member owned co-operative?
  - private (boolean): True/False is it a private company? Public owned utility (POU)?
  - geom: determined by the look-up table `provides_electricity_to` because corporate entities do not have an intrinsic spatial component. For instance, AVEC and Alaska Power and Telephone serve isolated communities so their sevice regions are discontinuous.

### PowerLines
- **Definition**: The transmission and distribution lines that create a Grid that includes multiple Communities. In Electric North, there was a distinction between the voltages of transmission and distribution lines, but that was arbitrarily defined and changed as needed. 
- **SpatialRelationships**: 
  - WITHIN Grids
  - TOUCHES PowerStations
  - TOUCHES Loads
- **Analogous Standards**:
   - [OEO:electricity grid component](http://openenergy-platform.org/ontology/oeo/OEO_00000144)  (a material entity that includes power plants)
  - or more specifically [OEO:power line](http://openenergy-platform.org/ontology/oeo/OEO_00000253)
  - [dc:PhysicalResource](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/PhysicalResource)
- **Properties**:
  - owner (string): Who owns it?
  - maintainer (string): Who maintains it? Is this the same as Owner?
  - voltage (int): voltage of line in kV (by definition above 69 kV for transmission lines, but not always in Alaska)
  - type (string): buried, underwater, overhead
  - geometry (WKT MultiLineString): polyline that traces an acceptible, if not accurate, route of the lines.

### PowerStations
- **Definition**: Entities that generate electricity for grids. 
- **SpatialRelationships**: 
  - TOUCHES PowerLines
  - WITHIN Grids
- **Analogous Standards**:
  - [dc:PhysicalResource](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/PhysicalResource)
  - [OEO:power plant](http://openenergy-platform.org/ontology/oeo/OEO_00000031) - "an energy transformation unit consisting of power generating units and a grid component that feeds electric energy into an electric grid."
- **Properties**:
  - fuel (string): OK. now I know this belongs elsewhere, because fuel type should be a lookup table and that doesn't belong with communities. Perhaps already handled by the Open Energy Ontology.
  - geometry (WKT Point):


## Optional

### CensusArea
- **Definition**: Census areas are subdivisions of the unorganized borough that are only used for statistical analysis and do not have a government of their own. These are typically undeveloped areas, so I'm not sure how relevant they are for AEDG.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/DefinedRegion - Arbitrary!  haha
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of the unincorporated Borough)
- **References**:
  - https://gis.data.alaska.gov/datasets/DCCED::alaska-borough-and-census-area-boundaries/about
- **Properties**:
  - boundary (WKT Polygon): longitude, latitude points that denote the boundary of the census area.


### ZipCode
- **Definition**: Postal zip codes as available from [link] (ZCTA)
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/DefinedRegion - properties of which were designed for zip codes
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of the United States and of Alaska)
- **References**:
  - https://www.geonames.org/postal-codes/US/AK/alaska.html (place = town, Admin2 = borough?)
- **Properties**:
  - boundary (WKT Polygon): longitude, latitude points that denote the boundary of the house district.


### SchoolDistrict
- **Definition**: Community based school districts. This might be out of scope or better handled as research.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) for the governmental organization.
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of what?)
- **Properties**:
  - boundary (WKT Polygon): longitude, latitude points that denote the boundary of the school district. This is too much to expect, probably.



