---
title: "Regional Classes"
subtitle: "Types of entities in the Alaska Community Ontology"
date: 2025-05-23
---


## AEDG Context Only

### Communities
- **Definition**: Construct of AEDG that is the fundamental unit of displays and dashboards.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/Place
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
- **Properties**:
  - fips_code (integer): Federal Information Processing Standard, identifying geographic locations. unique identifier.
  - geometry (WKT Point): longitude, latitude of the Community for convenience of display. Perhaps the centroid of the Municipality or a commonly accepted "place".
  - geometry (WKT Polygon): boundary of the administrative bounds of a Community.


## ANCSA or Indigenous Context

### FedRecognizedTribes
- **Definition**: There are 229 Federally recognized Tribes according to "Indian Entities Recognized and Eligible to Receive Services from the United States Bureau of Indian Affairs" (January 28, 2022), 87 Federal Register 4636. AEDG associates Communities with  Alaska Native village corporations and Alaska Native regional corporations.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/GovernmentOrganization
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
- **References**:
  - https://biamaps.geoplatform.gov/BIA-Opendata/Data/ has several relevant layers
  - https://www.fws.gov/sites/default/files/documents/Map-Federally-Recognized-Tribes-In-Alaska.pdf
  - https://www.federalregister.gov/documents/2022/01/28/2022-01789/indian-entities-recognized-by-and-eligible-to-receive-services-from-the-united-states-bureau-of
- **Properties**:


### VillageCorps
- **Definition**: Alaska Native village corporations were created by the Alaska Native Claims Settlement Act (ANCSA) and are organized around small communities. There is not a one to one correspondence between place and village corporations. For instance, The Kuskokwim Corporation (TKC) is merger of ten (Lower Kalskag, Kalskag, Aniak, Chuathbaluk, Napaimute, Crooked Creek, Georgetown, Red Devil, Sleetmute, and Stony River) and the headquarters of some are in Anchorage. In the energy context, a village corporations might operate an Independent Power Producer that sells power to Electric Utilities.  
- **SpatialRelationships**: 
  - WITHIN Alaska
  - NEAR Communities
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
  - Is an [foaf:Organization](http://xmlns.com/foaf/spec/#term_Organization) that is [foaf:based_near](http://xmlns.com/foaf/spec/#term_based_near) a Community - "A location that something is based near, for some broadly human notion of near."
- **References**:
  - https://ancsa.lbblawyers.com/1602.htm (definition)
  - https://ancsaregional.com/about-ancsa/#mandates
  - https://ancsa.lbblawyers.com/native-corporations.htm (list of 179)
  - https://dcra-cdo-dcced.opendata.arcgis.com/datasets/DCCED::native-village-corporations/ (215 records)
  - https://dnr.alaska.gov/mlw/paad/17b-easements/search/ (list of 245)
  - https://kuskokwim.com/
- **Properties**:
  - geometry (WKT Point): longitude, latitude of place or of headquarters


### RegionalCorps
- **Definition**: Alaska Native regional corporations were created by the Alaska Native Claims Settlement Act (ANCSA). The boundaries of these areas do not directly represent land ownership, but instead define the areas in which each regional corporation could select lands to be conveyed under the provisions of ANCSA.
- **SpatialRelationships**: 
  - WITHIN Alaska
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
- **References**:
  - https://www.arcgis.com/home/item.html?id=c78df0004ab845a9a32697d9c20d09e0
  - https://catalog.data.gov/dataset/tiger-line-shapefile-2017-state-alaska-current-alaska-native-regional-corporation-anrc-state-ba
  - https://ancsa.lbblawyers.com/native-corporations.htm (list of 13)
  - https://ancsaregional.com/about-ancsa/#mandates
  - https://maps.commerce.alaska.gov/server/rest/services/ANCSA/ANCSA_Corporations/MapServer
- **Properties**:
  - geometry (WKT Polygon): boundary of the RegionalCorp.
  - Additional properties should be determined by what is important to the people.


## Administrative Context

### IncorporatedPlaces
- **Definition**: Incorporated places are legally incorporated under state law, have a legally defined boundary, and an active functioning governmental structure. Examples of incorporated places include cities, towns, villages, etc. (Not boroughs in Alaska)
- **SpatialRelationships**: 
  - WITHIN Boroughs
  - WITHIN Precincts
  - WITHIN HouseDistricts
  - WITHIN SenateDistricts
- **Analogous Standards**:
  - https://schema.org/GovernmentOrganization
  - has an https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location) for the place
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) for the government
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents. It is unclear if a government can be a provider.
- **References**:
  - https://www.census.gov/programs-surveys/bas/information/cdp.html
  - https://www2.census.gov/programs-surveys/popest/tables/2020-2023/cities/totals/SUB-IP-EST2023-POP-02.xlsx 2023 populations for Alaska incorporated places
- **Properties**:
  - geometry (WKT Polygon): boundary 


### CensusDesignatedPlaces
- **Definition**: CDPs are statistical equivalents of incorporated places and represent unincorporated communities that do not have a legally defined boundary or an active, functioning governmental structure. They are locally recognized and identified by name. Examples of CDPs include unincorporated communities, planned communities, military installments, university towns, resort towns, etc. 
- **SpatialRelationships**: 
  - WITHIN Boroughs
  - WITHIN Precincts
  - WITHIN HouseDistricts
  - WITHIN SenateDistricts
- **Analogous Standards**:
  - https://schema.org/Place
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
- **References**:
  - https://www.census.gov/programs-surveys/bas/information/cdp.html
- **Properties**:
  - location (WKT Point): longitude, latitude points
  - population


### Boroughs
- **Definition**: Boroughs are analogous to counties in other states with several Alaska-specific qualities. First, boroughs were initially formed in areas whose economies were better developed at the time; the remaining areas were consolidated as the Unorganized Borough. Second, for statistical purposes the Unorganized Borough is divided into Census Areas; these do not have governments of their own. Third, there are also areas where city and borough governments have been consolidated.
- **SpatialRelationships**: 
  - CONTAINS IncorporatedPlaces
  - CONTAINS CensusDesignatedPlaces
  - OVERLAPS Precincts
  - OVERLAPS HouseDistricts
  - OVERLAPS SenateDistricts
- **Analogous Standards**:
  - https://schema.org/GovernmentOrganization
  - has an https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location) for the place
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) for the government
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of Alaska)
  - OEO:provider (an organization with a role) provides a governmental OEO:service
- **References**:
  - https://gis.data.alaska.gov/datasets/DCCED::alaska-borough-and-census-area-boundaries/about
  - https://www.commerce.alaska.gov/web/dcra/LocalBoundaryCommission
  - https://en.wikipedia.org/wiki/List_of_boroughs_and_census_areas_in_Alaska
  - https://live.laborstats.alaska.gov/cen/maps/state/current/AlaskaBorCA.pdf
  - https://live.laborstats.alaska.gov/cen/maps/bor/current/090.pdf map of FNSB with cities and census
- **Properties**:
  - type (string): "Unified Home Rule", "Non-unified Home Rule", "First Class", "Second Class"
  - geometry (WKT MultiPolygon): boundary of the Borough


### HouseDistricts
- **Definition**: The Alaska State House is the lower house in the Alaska State Legislature. Its districts are determined on the basis of population and shall be "contiguous and compact territory containing nearly as possible a relatively integrated socioeconomic area"
- **SpatialRelationships**: 
  - CONTAINS IncorporatedPlaces
  - CONTAINS CensusDesignatedPlaces
  - CONTAINS Precincts
  - WITHIN SenateDistricts
- **Analogous Standards**:
  - https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of Alaska and of SenateDistrict)
- **References**:
  - https://maps.commerce.alaska.gov/server/rest/services/Govt_Related/Govt_House_and_Senate_Districts/MapServer
  - https://www.elections.alaska.gov/doc/forms/H07.pdf list of senate and house districts
  - https://www.elections.alaska.gov/doc/forms/H32COM.pdf community/district lists
  - https://akleg.gov/pages/legbranch.php
- **Properties**:
  - district (int): digit that denotes the district
  - geometry (WKT MultiPolygon): boundary of the district.


### SenateDistricts
- **Definition**: Alaska State Senate is the upper house in the Alaska State Legislature. Its districts are composed of two contiguous house districts, if possible.
- **SpatialRelationships**: 
  - CONTAINS IncorporatedPlaces
  - CONTAINS CensusDesignatedPlaces
  - CONTAINS Precincts
  - CONTAINS HouseDistricts
- **Analogous Standards**:
  - https://schema.org/AdministrativeArea
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of Alaska)
- **References**:
  - https://maps.commerce.alaska.gov/server/rest/services/Govt_Related/Govt_House_and_Senate_Districts/MapServer
 - https://www.elections.alaska.gov/doc/forms/H07.pdf list of senate and house districts
 - https://www.elections.alaska.gov/doc/forms/H32COM.pdf community/district lists
 - https://akleg.gov/pages/legbranch.php
- **Properties**:
  - district (character): Capitol letter that denotes the district
  - geometry (WKT MultiPolygon): boundary of the district.

### SchoolDistrict
- **Definition**: Community based school districts. This might be out of scope or better handled as research.
- **SpatialRelationships**: 
- **Analogous Standards**:
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent) for the governmental organization.
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance.
- **Properties**:
  - boundary (WKT Polygon): longitude, latitude points that denote the boundary of the school district.


## Statistical or Research Context

### CensusBlocks
- **Definition**: Census blocks are the smallest level of geography you can get basic census demographic data for, such as total population by age, sex, and race.
- **SpatialRelationships**: 
  - WITHIN CensusTracts
- **Analogous Standards**:
  - https://schema.org/DefinedRegion as a broad definition
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:study subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020034) (of CensusTract)
- **References**:
  - https://www.census.gov/newsroom/blogs/random-samplings/2011/07/what-are-census-blocks.html
  - https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geopackage-file.html
  - https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html
  - https://live.laborstats.alaska.gov/article/maps-gis-data
- **Properties**:
  - geometry (WKT Polygon): boundary of the census block.


### CensusTracts
- **Definition**: Census tracts are small, relatively permanent statistical subdivisions of a county or statistically equivalent entity that provide a stable set of geographic units for the presentation of statistical data.
- **SpatialRelationships**: 
  - CONTAINS CensusBlocks
- **Analogous Standards**:
  - https://schema.org/DefinedRegion as a broad definition
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:study region](http://openenergy-platform.org/ontology/oeo/OEO_00020032) - "A study region is a region of relevance that has the study region role and consists entirely of one or more subregions."
- **References**:
  - https://www.census.gov/programs-surveys/geography/about/glossary.html#par_textimage_13
  - https://esri.maps.arcgis.com/home/item.html?id=20f5d275113e4066bf311236d9dcc3d4
  - https://live.laborstats.alaska.gov/article/maps-gis-data
- **Properties**:
  - geometry (WKT Polygon): boundary of the census tract.

### CensusArea

see Boroughs

### AeaEnergyRegions {#sec-aea-energy-regions}
- **Definition**: Energy Regions as defined by Alaska Energy Authority for Regional Energy Planning. These were also used in the Alaska Energy Statistics Reports.
- **SpatialRelationships**: 
  - CONTAINS Communities
- **Analogous Standards**:
  - https://schema.org/DefinedRegion as a broad definition
  - [OEO:study region](http://openenergy-platform.org/ontology/oeo/OEO_00020032) - "A study region is a region of relevance that has the study region role and consists entirely of one or more subregions."
- **References**:
  - https://dcra-cdo-dcced.opendata.arcgis.com/datasets/DCCED::alaska-energy-authority-regions/about
  - https://gis.data.alaska.gov/datasets/DCCED::energy-development-regions/explore?location=0.934218%2C0.000000%2C0.91&showTable=true
- **Properties**:
  - geometry (WKT Polygon): borders of the study regions

### AcepEnergyRegions
- **Definition**: Communities were been grouped into 3 regions in order to summarize energy trends in the [2024 Alaska Electricity Trends Report](https://acep-uaf.github.io/aetr-web-book-2024/). Was intended to group communities by generation mix, but we grouped in contiguous areas: railbelt, coastal, and rural remote.
- **SpatialRelationships**: 
  - CONTAINS Communities
- **Analogous Standards**:
  - https://schema.org/DefinedRegion as a broad definition
  - [OEO:study region](http://openenergy-platform.org/ontology/oeo/OEO_00020032) - "A study region is a region of relevance that has the study region role and consists entirely of one or more subregions."
- **Properties**:
  - geometry (WKT MultiPolygon) or (WKT Polygon): boundaries 

### DrcaEconomicRegions
- **Definition**: The Alaska Division of Community and Regional Affairs (DCRA) distributes some data grouped by Alaska economic regions, which are based on 2013 borough and census area geography with boundaries determined by the Alaska Department of Labor & Workforce Development. 
- **SpatialRelationships**: 
  - CONTAINS Communities
- **Analogous Standards**:
  - https://schema.org/DefinedRegion as a broad definition
  - [OEO:study region](http://openenergy-platform.org/ontology/oeo/OEO_00020032) - "A study region is a region of relevance that has the study region role and consists entirely of one or more subregions."
- **References**:
  - https://maps.commerce.alaska.gov/server/rest/services/Boundaries/CDO_Economic_Regions/MapServer/0
  - https://gis.data.alaska.gov/datasets/DCCED::economic-regions-2/about
- **Properties**:
  - CommunityName: 6 regional names like Anchorage, Interior, and Southeast
  - DataYear: 
  - LocalLaborMarketInfoURL: link to http://live.laborstats.alaska.gov/alari/ (which is 404)
  - geometry (WKT Polygon): boundaries 

### ZipCode
- **Definition**: Postal zip codes as available from [link] (ZCTA)
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://schema.org/DefinedRegion - properties of which were designed for zip codes
  - [dc:Location](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Location)
  - [OEO:subregion](http://openenergy-platform.org/ontology/oeo/OEO_00020033) - a region of relevance that is in every respect a component of a region of relevance, but never encompasses the entire extent of a region of relevance. (of the United States and of Alaska)
- **References**:
  - https://www.geonames.org/postal-codes/US/AK/alaska.html (place = town, Admin2 = borough?)
- **Properties**:
  - boundary (WKT Polygon): longitude, latitude points that denote the boundary of the house district.
