---
title: "Fuel, Heating, Thermal, and Transportation Classes"
subtitle: "Descriptions of Energy-related entities (besides Electricity) in the Alaska Community Ontology"
date: 2025-05-28
---

Unfortunately, without specific data sources to provide and constrain attributes, some classes and relationships cannot yet be defined within the context of AEDG. As data sources are identified in @sec-energy-data, this page will evolve. For now, it is incomplete.


## Fuel (not natural gas) {#sec-fuel}

### DCRA's Heating and Gasoline Surveys
- **Definition**: In 2005, the Division of Community and Regional Affairs (DCRA) began collecting prices of heating fuel and unleaded gasoline in 100 select communities. The prices for heating fuel in these 100 communities are collected via a telephone survey of each fuel retailer. The communities have remained constant since the project’s inception and the reported prices should be considered representative of what a community resident would have paid for a gallon of heating fuel (including tax) on the day of contact. Values are also presented as averages for DCRA Economic Regions.
- **SpatialRelationships**: 
  - INTERSECTS Communities (as in only includes some)
  - Averaged into DrcaEconomicRegions
- **Analogous Standards**:
  - [OEO:gasoline](http://openenergy-platform.org/ontology/oeo/OEO_00000183) 
  - [OEO:heating oil](http://openenergy-platform.org/ontology/oeo/OEO_00000211)
  - [OEO:monetary price](http://openenergy-platform.org/ontology/oeo/OEO_00020427)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities, in this case fuel
- **References**:
  - https://storymaps.arcgis.com/stories/6d6a33a3d9a74723a2f476c26ecfdf21
  - https://maps.commerce.alaska.gov/server/rest/services/Services/CDO_Utilities/MapServer/61
  - https://maps.commerce.alaska.gov/server/rest/services/Services/CDO_Utilities/MapServer/45
  - https://gis.data.alaska.gov/datasets/DCCED::heating-fuel-price-all-years/about
  - https://gis.data.alaska.gov/datasets/DCCED::gas-prices-all-years/about
  - https://gis.data.alaska.gov/maps/DCCED::fuel-delivery-method
- **Properties**:
  - Community (100) or Economic Region
  - Heating Fuel Retail Price Per Gallon
  - Heating Fuel Vendor
  - Gas Retail Price Per Gallon
  - Gas Vendor
  - Reporting Year: survey year (since 2005)
  - Reporting Season: summer or winter
  - geometry (WKT Point) or (WKT Polygon): 100 points for communities and boundaries for economic regions


### DCRA Fuel Distribution from the Community Surveys
- **Definition**: The process of delivering heating oil and gasoline to 100 surveyed Communities 
- **SpatialRelationships**: 
- **Analogous Standards**:
  - https://gis.data.alaska.gov/datasets/DCCED::fuel-delivery-method/about
  - [OEO: distribution](http://openenergy-platform.org/ontology/oeo/OEO_00010136): "Distribution is the process of delivering goods and services to agents"
  - [OEO: fuel](http://openenergy-platform.org/ontology/oeo/OEO_00000173)
- **References**:
  - https://gis.data.alaska.gov/datasets/DCCED::fuel-delivery-method/about is "Primary method by which a community receives its fuel shipments according to the biannual DCRA Alaska Fuel Survey."
- **Properties**:
  - CommunityName
  - Fuel Delivery Method: Barge, Plane, Road, Ice Road (not Rail?)
  - AsOfDate: when the survey was performed
  - geometry (WKT Point) : 100 points for communities


### Propane

- [OEO: liquefied petroleum gas](http://openenergy-platform.org/ontology/oeo/OEO_00320011): "Liquefied petroleum gas (LPG) is gas mixture of hydrocarbon gases, mainly propane and butane."

### Bulk Fuel Storage

- [OEO: fuel tank](http://openenergy-platform.org/ontology/oeo/OEO_00320056)

## Natural Gas

### RCA Regulated Natural Gas Utilities
- **Definition**: A corporation, person, agency, authority, or other legal entity or instrumentality aligned with distribution facilities for furnishing by transmission or distribution of natural or manufactured gas to the public for compensation; 
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
  - [OEO: natural gas](http://openenergy-platform.org/ontology/oeo/OEO_00000292)
- **References**:
  - [RCA search](https://rca.alaska.gov/RCAWeb/RCALibrary/SearchResults.aspx?t=cert&p=typesearch&cert=&entity=&utiltype=41ccfb21-50d0-481e-aaf3-bd9c73153227) 
  - @sec-utility-definitions
- **Properties**:
  - certificate_number: RCA Certificate of Public Convenience and Necessity (CPCN) number
  - certificate_name: RCA's name for the utility
  - geom: service area

### RCA Regulated Natural Gas Storage

- [RCA search](https://rca.alaska.gov/RCAWeb/RCALibrary/SearchResults.aspx?t=cert&p=typesearch&cert=&entity=&utiltype=27421552-89e9-43c5-a783-101051f39f54)

### Liquefied Natural Gas Storage

- [OEO: liquefied natural gas](http://openenergy-platform.org/ontology/oeo/OEO_00010237): "Liquefied natural gas (LNG) is natural gas that has a liquid state of matter."

## Pipelines and Infrastructure

- [OEO: distribution](http://openenergy-platform.org/ontology/oeo/OEO_00010136): "Distribution is the process of delivering goods and services to agents" ?


## Heating

### Residential Space Heating

- See costs of heating oil as @sec-fuel
- [OEO: heating and cooling sector](http://openenergy-platform.org/ontology/oeo/OEO_00000213)

### Wind to Heat


## Thermal (Steam and Hot Water Utilities, Waste Heat, Heat Recovery)

### RCA Regulated Steam Heat Utilities
- **Definition**: A corporation, person, agency, authority, or other legal entity or instrumentality aligned with distribution facilities for furnishing water, steam, or sewer service to the public for compensation. 
- **Analogous Standards**:
  - https://schema.org/Corporation
  - [dc:Agent](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent)
  - [OEO:provider](http://openenergy-platform.org/ontology/oeo/OEO_00140123) - A provider is an agent (organization) that transfers commodities or a [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) to other agents.
  - [OEO: heating and cooling sector](http://openenergy-platform.org/ontology/oeo/OEO_00000213)
  - [OEO: district heating](http://openenergy-platform.org/ontology/oeo/OEO_00000132)
  - [OEO: heating grid component](http://openenergy-platform.org/ontology/oeo/OEO_00020008)
- **References**:
  - [RCA search](https://rca.alaska.gov/RCAWeb/RCALibrary/SearchResults.aspx?t=cert&p=typesearch&cert=&entity=&utiltype=bcff05fe-74e7-4c68-b9a8-ca3469ef5f86)
  - @sec-utility-definitions
- **Properties**:
  - certificate_number: RCA Certificate of Public Convenience and Necessity (CPCN) number
  - certificate_name: RCA's name for the utility
  - geom: service area


### Combined Heat and Power (CHP)
- **Definition**:  From OEO, "A combined heat and power plant (CHPP) is an energy transformation unit that consists of combined heat and power generating units, a grid component feeding electric energy into an electricity grid, and a grid component feeding thermal energy into a heating grid."
- **SpatialRelationships**:
  - CHP plants provide heat to nearby buildings (Touches?)
  - CHP plants are Within Communities
  - TOUCHES PowerLines
  - WITHIN Grids
- **Analogous Standards**:
  - [OEO: combined heat and power plant](http://openenergy-platform.org/ontology/oeo/OEO_00240011)
  - [OEO: heating and cooling sector](http://openenergy-platform.org/ontology/oeo/OEO_00000213)
  - [OEO: district heating](http://openenergy-platform.org/ontology/oeo/OEO_00000132)
  - [OEO: heating grid component](http://openenergy-platform.org/ontology/oeo/OEO_00020008)
- **References**:
  - DOE's [Combined Heat and Power Installations in Alaska](https://doe.icfwebservices.com/state/chp/AK)
  - There is a boolean column for this in the [Alaska Energy Statistics Workbooks](https://acep-uaf.github.io/ak-energy-statistics-2011_2021/) Generation Plants table
- **Properties**: based on DoE's database
  - City: Community
  - Organization Name: operator
  -	Facility Name: system name (like "Baxter Senior Living Center" or "Angoon")
  - Application: like "Remote Community", "Nursing Homes", or "Hospitals/Healthcare"
  - SIC4: Standard Industrial Classification is a system for classifying industries (from OHSA)
  - NAICS: North American Industry Classification System (NAICS) for classifying business (from census)
  - OpYear
  - Latest Install Year
  - Capacity (kW)
  - Prime Mover: like "Reciprocating Engine" or "Organic Rankine Cycle"
  -	Fuel Class Prim Fuel: coal, oil, propane, natural gas, etc 
  - Last Verified	Project Profile Link	
  - Microgrid: is it part of a microgrid?
  - Critical Infrastructure: does it provide essential services and functions?


### Waste Heat to Power (WHP)
- **Definition**:  EPA's definition is "Waste heat to power (WHP) is the process of capturing heat discarded by an existing
thermal process and using that heat to generate power"
- **SpatialRelationships**: 
  - TOUCHES PowerLines
  - WITHIN Grids
- **Analogous Standards**:
  - [OEO: power plant](http://openenergy-platform.org/ontology/oeo/OEO_00000031) - "an energy transformation unit consisting of power generating units and a grid component that feeds electric energy into an electric grid."
  - [OEO: waste power plant](http://openenergy-platform.org/ontology/oeo/OEO_00000440) may be this, or it might be from refuse (i.e. garbage)
- **References**:
  - EPA's definition [Waste Heat to Power Systems](https://www.epa.gov/sites/default/files/2015-07/documents/waste_heat_to_power_systems.pdf)
  - Unalaska 2015c announced [Rankin Cycle (ORC) heat recovery generators](https://www.ci.unalaska.ak.us/publicutilities/page/waste-heat-recovery-project) at the Dutch Harbor Power Plant.
    - Unalaska's WHP does not seem to be in the [Alaska Energy Statistics Workbooks](https://acep-uaf.github.io/ak-energy-statistics-2011_2021/) Generation Plants table
- **Properties**:
  - unknown


## Geothermal and Community-scale Ground Source Heat Pumps

- [OEO: geothermal heat plant](http://openenergy-platform.org/ontology/oeo/OEO_00310018)
- [OEO: geothermal power plant](http://openenergy-platform.org/ontology/oeo/OEO_00000192)
- [OEO: heat pump](http://openenergy-platform.org/ontology/oeo/OEO_00000212)


## Transportation

### DCRA's Transportation Overview 
- **Definition**:  
- **SpatialRelationships**: 
  - Transportation joins communities
  - Transportation joins communities to services
- **Analogous Standards**:
  - [OEO: transport network](http://openenergy-platform.org/ontology/oeo/OEO_00320016): "A transport network is a supply system of transport network components that enables the transport of people and/or goods."
- **References**:
  - https://maps.commerce.alaska.gov/server/rest/services/Transportation/Transportation_Overview/MapServer/0
  - [DCCED Transportation dashboard](https://dcced.maps.arcgis.com/apps/webappviewer/index.html?id=3de3ebccbb6b4ba8a9c64609e96199ba)
  - https://gis.data.alaska.gov/datasets/DCCED::community-transportation-overview/about
- **Properties**:
  - airport: Answers the question: Does the Community have an airport?
  - cargo_barge: Answers the question: Is the Community served by a cargo barge?
  - coastal: Answers the question: Is the Community located on the coast?
  - harbor_dock: Answers the question: Does the Community have a harbor with a dock? 
  - road_connection:Answers the question: Is the Community connected to a road system to other communities?
  - state_ferry: Answers the question: Is the Community served by a state ferry?
  - description: a narrative summary of transportation options

### Electric Vehicles

- [OEO: electric vehicle](http://openenergy-platform.org/ontology/oeo/OEO_00000146)
- [OEO: vehicle charging station](http://openenergy-platform.org/ontology/oeo/OEO_00320040)
