---
title: "Relations"
subtitle: "Domain-defined ways that entities relate to each other in the Alaska Community Ontology"
author:
  - name: Liz Dobbins
    url: https://github.com/eldobbins
    affiliation: "Alaska Center for Energy and Power, University of Alaska Fairbanks"
    affiliation-url: https://www.uaf.edu/acep 
type: webpage
date: 2024-11-12
---

Relations can be heirarchical (taxonomy) or could form a network or graph (semantic web) of the various entities. These are based on domain specific rules (Axioms), and that defines an ontology. Relations enable AI to infer new information without people having to explicitly define everything.

  - Relations are the edges in a graph.
  - In a relational database, Relations can be encoded using a lookup table with a combination of foreign keys.


## Applicable Standards

[ArcMap spatial relations](https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/relational-functions-for-st-geometry.htm)

- ST_Contains
- ST_Crosses
- ST_Disjoint
- ST_Equals
- ST_Intersects
- ST_Overlaps
- ST_Relate
- ST_Touches
- ST_Within

[GeoSPARQL](https://docs.ogc.org/is/22-047r1/22-047r1.html) - same except for Relate

- geor:sfContains
- geor:sfCrosses
- geor:sfDisjoint
- geor:sfEquals
- geor:sfIntersects
- geor:sfOverlaps
- geor:sfTouches
- geor:sfWithin

[OBO Relations Ontology](https://www.ebi.ac.uk/ols4/ontologies/ro?tab=properties) "is a collection of OWL relations (ObjectProperties) intended for use across a wide variety of biological ontologies." It is a foundational element of the [Open Energy Ontology](http://openenergy-platform.org/ontology/oeo/).

On the other hand, in the OEO [Terminology Service](https://terminology.tib.eu/ts/ontologies/oeo/props), I could only find one instance of a straight-up `RO` usage: [is homeomorphic for](https://terminology.tib.eu/ts/ontologies/oeo/props?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0040042) (which I don't even understand).

# Relations

## Spatial Relations

Most relationships can be established dynamically through spatial relations. We do not need to have a lookup table of Communities in Boroughs, say, because we can select all the Community points that the Borough CONTAINS. The primary relationships are sketched out on the Classes pages, but the combinations are really unlimited.

## Lookup Tables

Some classes are legal or corporate entities and so do not have an intrinsic spatial component. But they serve other entities that _do_ have a spatial component, so we will use look-up tables to attach spatial info to them.

It would be great if the table names could be based on an established ontology. Liz is currently looking into this. However, in the meantime, table names are very specific so that they describe the exact relationship between the entities. This will self-document the queries when those are written.

Here are the look-up tables that will do this:

## provides_electricity_to

Utilites provide electricity to Communities. Liz added some columns that might be useful, but she doesn't know where these data will come from, so the table schema will change. This is just an example of what _could_ be.
- **Analogous Standards**:
 - [OEO:Service](http://openenergyplatform.org/ontology/oeo/OEO_00140124/) - "A service is a process that is an intangible activity performed by some agent for the benefit of another agent."
 - [Schema.org:Service](https://schema.org/Service) - "A service provided by an organization, e.g. delivery service, print services, etc."


| id_provides | id_utility | id_community | year_established | 
| ----------- | ---------- | ------------ | ---------------- |
| integer     | integer    | integer      | integer          |


## is_intertied_with

Grids are connected to each other with interties. Interties are the physical power lines (transmission or distribution) that make the connection, but "intertie" is also the action of making two separate Grids into a new Grid. An intertie can be multiple lines going on different routes so if a geometry was defined, the line might be quite complex; for our puposes, we will start by representing interties with lines that join the Community points. Interties have a start date that could be defined in multiple ways - date of construction or date when billing changed. (This needs clarification.) 
- **Analogous Standards**:
  - OEO:electricity grid component  (a material entity that includes power plants)
  - or maybe more specifically OEO:power line
  - [dc:PhysicalResource](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/PhysicalResource)
- **Properties**:
  - owner (string): Who owns it?
  - maintainer (string): Who maintains it? Is this the same as Owner?

This is just an example of what _could_ be. Schema should be based on Neil's work?

| id_intertie | id_grid1 | id_grid2 | new_grid_id | year_established | owner  | maintainer |
| ----------- | -------- | -------- | ----------- | ---------------- | ------ | ---------- |
| integer     | integer  | integer  | integer     | integer          | string | string     |

